### ISSUE TITLE
caching markdown blocks

### ISSUE THREAD

**Issue by slimslenderslacks** [docker/labs-ai-tools-vscode#1]
This is so that you don't have to open/edit runbooks in order to bind commands.

The LSP now supports a `request` called `docker/markdown-blocks` which will cause the lsp to re-fire all of the current `$bind/register` notifications using whatever has been cached.  If the runbook.md has ever been opened by the user on the current machine (the current docker-lsp volume) then you'll be notified of those cached volumes.

**Comment by ColinMcNeil** [comment]
Implemented ✅
