### ISSUE TITLE
Missing Docker Engine error is hard to interpret

### ISSUE THREAD

**Issue by slimslenderslacks** [docker/labs-ai-tools-vscode#21]
Reproduction

1. Stop Docker engine
2. Start VScode
3. Choose "Generate runbook"

![CleanShot 2024-06-10 at 17 20 30](https://github.com/docker/labs-make-runbook/assets/1643888/70a41da4-37c5-471d-8dad-baaf14b21fa3)

Can this be something closer to "No local Docker Engine detected" just so we can be more prescriptive.

**Comment by ColinMcNeil** [comment]
Resolved in #23

**Comment by slimslenderslacks** [comment]
@ColinMcNeil this fix didn't work for me when I tried it with a local build.

**Comment by ColinMcNeil** [comment]
How are you stopping the docker engine? I am seeing this work when I quit docker desktop and restart it.
