### ISSUE TITLE
Json: Error: Connection error.

### ISSUE THREAD

**Issue by jovicon** [docker/labs-ai-tools-vscode#35]
Hi, I tried make runbook v0.0.10

and I had this problem:

```json
Error: Connection error.
```

This is my docker file:

```Dockerfile
FROM node:20.13.1-alpine

# Docker Scout -- Vulnerability Scanning solved
RUN apk upgrade busybox 
RUN apk upgrade openssl 

WORKDIR /usr/src/app

COPY ["package.json", "./"]
COPY [".env.example", "./.env"]

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD node ./dist/src/main.js
```

**and this is my extension config:**

![Captura de Pantalla 2024-06-21 a la(s) 18 27 54](https://github.com/docker/labs-make-runbook/assets/21287303/0fe298b7-0857-469f-ae7b-e17800a969a7)

**Comment by ColinMcNeil** [comment]
Hi, thanks for submitting this issue. At the moment, we only support the Ollama endpoint `http://localhost:11434/v1` so if you have it running elsewhere this would cause the error.

**Comment by jovicon** [comment]
Is it possible to take this as an issue with a Merge request and add a custom field to add the local endpoint?

**Comment by slimslenderslacks** [comment]
@jovicon we've been migrating these runbook prompts to allow you to specify the url in the prompt.  So you'll be able to specify the location of the OpenAI compatible endpoint when you run the prompt.  It's a bit of a different flow than what we used previously but it will be more open to edits.  I'll keep this issue open until we have a doc describing how you can try this.

**Comment by ColinMcNeil** [comment]
Closing this one! Please feel free to checkout the main repo with new docs at https://github.com/docker/labs-ai-tools-for-devs. Support llama with the following front-matter
```
---
url: http://llama-endpoint.local/
model: llama3.2
---

# prompt system
Prompt content
```
