### ISSUE TITLE
Add --pat back

### ISSUE THREAD

**Issue by slimslenderslacks** [docker/labs-ai-tools-vscode#41]
Can you please rollback merge request #39 (remove the pat). I think we should keep this method active in the short term.

**Comment by ColinMcNeil** [comment]
You resolved this yourself I think?

**Comment by slimslenderslacks** [comment]
@ColinMcNeil No, I didn't resolve this.

**Comment by ColinMcNeil** [comment]
Apologies, I was on `labs-ai-tools-for-devs`.

Resolved with https://github.com/docker/labs-ai-tools-vscode/commit/d7d309c3889224e797f2218788fb21bdc28a2eaf
